# Generated by Django 4.1 on 2022-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0006_rename_wifi_passsword_restaurantinfo_wifi_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='rest_phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефону ресторану'),
        ),
    ]
